import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { League_Spartan } from "next/font/google";
import { Footer } from "@/components/Footer";
import { LoadingBar } from "@/components/LoadingBar";
import { Suspense } from "react";
// import { Navbar } from "@/components/Navbar";
import dynamic from 'next/dynamic'




// Configure Spartan (League Spartan)
const spartan = League_Spartan({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-spartan",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Navbar = dynamic(() => import('@/components/Navbar').then(mod => ({ default: mod.Navbar })), {
  ssr: true, 
  loading: () => (
    <nav className="w-full bg-white h-32 animate-pulse">
      {/* Skeleton loader */}
      <div className="max-w-7xl mx-auto px-4 h-full flex items-center justify-center">
        <div className="h-16 w-48 bg-gray-200 rounded"></div>
      </div>
    </nav>
  )
})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spartan.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <Suspense fallback={<div>Loading...</div>}>
          <Navbar />
          <LoadingBar />
          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
